version: '3.8'

services:
  web:
    build: .
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./.:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sure_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sure_app

volumes:
  postgres_data:

      